Separate out Torch libs from server
facebookresearch/fairo pull request #667
Opened 2021-08-18 23:00 UTC by 1heart

# Description

In preparation for compiling Polymetis without a custom Torch binary (CXX11_ABI=0).

Fixes # (issue)

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [ ] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change
- [ ] Datasets Release
- [ ] Models Release

## Type of requested review

- [ ] I want a thorough review of the implementation.
- [ ] I want a high level review. 
- [ ] I want a deep design review.

## Before and After

If this PR introduces a change or fixes a bug, please add before and after screenshots (if this is causes a UX change) or before and after examples(this could be plain text, videos etc ) to demonstrate the change.

If this PR introduces a new feature, please also add examples or screenshots demonstrating the feature.

# Testing

Please describe the tests that you ran to verify your changes and how we can reproduce.

# Checklist:

- [ ] I have performed manual end-to-end testing of the feature in my environment.
- [ ] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added relevant collaborators to review the PR before merge.

2021-08-18 23:25 UTC, 1heart commented
@soumith I isolated the Torch includes to only files within `torchscript_operators`.

Next steps from what I understand:
1. They're still using the C++ standard library, though. What needs to change here -- rewrite it in pure C, or limit usage of the standard library? (Can you provide an example within PyTorch that follows this?)
1. What do I need to do with the current PyTorch extensions (torchrot, and especially torchscript_pinocchio)?
1. Compile as a library separately using the official PyTorch binaries (cxx11_abi=0)
1. Link to it from Polymetis CMakeList

2021-11-04 00:21 UTC, exhaustin requested changes
Thanks for making this happen. Tbh I don't know what most of the isolation changes are doing, but looks reasonable on a high level. I also like the isolation of controller-related operations into an object.

A lot of the real time stack is being changed, so we definitely need to test extensively on hardware before merging. I can run the hardware CI tests.

2021-11-04 00:21 UTC, exhaustin commented on polymetis/polymetis/include/polymetis/polymetis_server.hpp
> +  TorchScriptedController *custom_controller;
shared_ptr?

2021-11-04 00:46 UTC, 1heart commented on polymetis/polymetis/torch_isolation/include/torch_server_ops.hpp
> +  struct TorchTensor *rs_motor_torques_external_;
I actually tried using smart pointers, but they apparently [don't play well with hidden implementations](https://stackoverflow.com/a/8915248/9654319). I'll implement a destructor.

2021-11-04 00:47 UTC, 1heart commented on polymetis/polymetis/include/polymetis/polymetis_server.hpp
> +  TorchScriptedController *custom_controller;
Same as above, will implement a destructor

2021-11-04 03:52 UTC, exhaustin commented on polymetis/polymetis/src/polymetis_server.cpp
> +  } catch (const std::exception &e) {
On second thought, maybe it's more straightforward if I stack a PR on top of this one that fixes this issue.

2021-11-04 14:10 UTC, 1heart commented on polymetis/polymetis/src/polymetis_server.cpp
> +          model_stream)) {
This should have the previous behavior, so I don't think so.

2021-11-04 20:21 UTC, exhaustin commented on polymetis/polymetis/src/polymetis_server.cpp
> +          model_stream)) {
Yeah after thinking about it we're not doing anything to make TorchScriptedController thread-safe, so this should be fine.

2021-11-04 20:25 UTC, exhaustin approved these changes
Looks good. Tasks before merging:
- Merging the stacked PR #785 to fix the blocking issue in SetController
- Fixing the valid context test that's not passing
- Testing on hardware, preferrably for long hours

2021-11-05 00:54 UTC, 1heart commented
@exhaustin if you could run the hardware CI for a couple of hours when you have time and then just merge it if it looks good

2021-11-06 16:25 UTC, exhaustin commented
Ran hardware CI for 1 hour straight. I got less than 10 communication constraint violations, which was definitely an improvement on the stability of SetController. 
Should be good to merge once tests pass.

2021-11-06 20:52 UTC, merged